#version: '3.8'
services:
  app1:
    build:
      context: .
      dockerfile: app1/Dockerfile
    image: app1:latest
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  app2:
    build:
      context: .
      dockerfile: app2/Dockerfile
    image: app2:latest
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  app3:
    build:
      context: .
      dockerfile: app3/Dockerfile
    image: app3:latest
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development