name: Cloud Run

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_IMAGE_1: app1
  DOCKER_IMAGE_2: app2
  DOCKER_IMAGE_3: app3
  PROJECT_ID: serverless-411207
  REGION: asia-southeast1
  REPOSITORY_ID: bdj-serverless-ci-cd-docker-repo
  CONNECTORS_ID: bdjserverlessvpcconnector
  GCP_SA_KEY: ${{ secrets.SERVERLESS_411207_C41760532440 }}

jobs:
  build-tag-push-deploy:
    name: Build, tag, push Docker image and deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: Production

    steps:
      # Continuous Integration
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        id: prep
        run: |
          VERSION="${{ github.run_number }}"
          REGISTRY="${REGION}-docker.pkg.dev"
          REPOSITORY="${REGISTRY}/${PROJECT_ID}/${REPOSITORY_ID}"
          TAG_DOCKER_IMAGE_1="${REPOSITORY}/${{ env.DOCKER_IMAGE_1 }}"
          TAG_DOCKER_IMAGE_2="${REPOSITORY}/${{ env.DOCKER_IMAGE_2 }}"
          TAG_DOCKER_IMAGE_3="${REPOSITORY}/${{ env.DOCKER_IMAGE_3 }}"
          echo "registry=${REGISTRY}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag_Docker_Image_1=${TAG_DOCKER_IMAGE_1}" >> $GITHUB_OUTPUT
          echo "tag_Docker_Image_2=${TAG_DOCKER_IMAGE_2}" >> $GITHUB_OUTPUT
          echo "tag_Docker_Image_3=${TAG_DOCKER_IMAGE_3}" >> $GITHUB_OUTPUT
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo ${TAG_DOCKER_IMAGE_1}
          echo ${TAG_DOCKER_IMAGE_2}
          echo ${TAG_DOCKER_IMAGE_3}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.prep.outputs.registry }}
          username: _json_key
          password: ${{ env.GCP_SA_KEY }}

      - name: Deploy with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          docker tag ${DOCKER_IMAGE_1} asia-southeast1-docker.pkg.dev/serverless-411207/bdj-serverless-ci-cd-docker-repo/${DOCKER_IMAGE_1}
          docker tag ${DOCKER_IMAGE_2} asia-southeast1-docker.pkg.dev/serverless-411207/bdj-serverless-ci-cd-docker-repo/${DOCKER_IMAGE_2}
          docker tag ${DOCKER_IMAGE_3} asia-southeast1-docker.pkg.dev/serverless-411207/bdj-serverless-ci-cd-docker-repo/${DOCKER_IMAGE_3}
          docker push asia-southeast1-docker.pkg.dev/serverless-411207/bdj-serverless-ci-cd-docker-repo/${DOCKER_IMAGE_1}
          docker push asia-southeast1-docker.pkg.dev/serverless-411207/bdj-serverless-ci-cd-docker-repo/${DOCKER_IMAGE_2}
          docker push asia-southeast1-docker.pkg.dev/serverless-411207/bdj-serverless-ci-cd-docker-repo/${DOCKER_IMAGE_3}

      # Continuous Deployment
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: '${{ env.PROJECT_ID }}'

      - name: Deploy to Cloud Run for DOCKER_IMAGE_1
        id: deploy1
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.DOCKER_IMAGE_1 }}
          region: ${{ env.REGION }}
          flags: --image ${{ steps.prep.outputs.tag_Docker_Image_1 }} --allow-unauthenticated --vpc-connector=projects/${{ env.PROJECT_ID }}/locations/${{ env.REGION }}/connectors/${{ env.CONNECTORS_ID }} --vpc-egress=all-traffic --set-env-vars=ASP_NET_CORE=development

      - name: Deploy to Cloud Run for DOCKER_IMAGE_2
        id: deploy2
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.DOCKER_IMAGE_2 }}
          region: ${{ env.REGION }}
          flags: --image ${{ steps.prep.outputs.tag_Docker_Image_2 }} --allow-unauthenticated --vpc-connector=projects/${{ env.PROJECT_ID }}/locations/${{ env.REGION }}/connectors/${{ env.CONNECTORS_ID }} --vpc-egress=all-traffic --set-env-vars=ASP_NET_CORE=development

      - name: Deploy to Cloud Run for DOCKER_IMAGE_3
        id: deploy3
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.DOCKER_IMAGE_3 }}
          region: ${{ env.REGION }}
          flags: --image ${{ steps.prep.outputs.tag_Docker_Image_3 }} --allow-unauthenticated --vpc-connector=projects/${{ env.PROJECT_ID }}/locations/${{ env.REGION }}/connectors/${{ env.CONNECTORS_ID }} --vpc-egress=all-traffic --set-env-vars=ASP_NET_CORE=development

      # Cloud Run URL output
      - name: Show Output for DOCKER_IMAGE_1
        run: echo ${{ steps.deploy1.outputs.url }}

      # Cloud Run URL output
      - name: Show Output for DOCKER_IMAGE_2
        run: echo ${{ steps.deploy2.outputs.url }}

      # Cloud Run URL output
      - name: Show Output for DOCKER_IMAGE_3
        run: echo ${{ steps.deploy3.outputs.url }}
